=== informationgrid/ingrid-editor/server/src/main/resources/bmi/schemes/bmi.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/definitions/BMI",
  "definitions": {
    "BMI": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_uuid": {
          "type": "string"
        },
        "_type": {
          "const": "OpenDataDoc"
        },
        "title": {
          "type": ["string", "null"],
          "minLength": 1
        },
        "events": {
          "type": ["null", "array"],
          "items": {
            "$ref": "#/definitions/Event"
          }
        },
        "landingPage": {
          "type": ["string", "null"]
        },
        "qualityProcessURI": {
          "type": ["string", "null"]
        },
        "spatial": {
          "type": ["array", "null"],
          "items": {
            "$ref": "#/definitions/Spatial"
          }
        },
        "politicalGeocodingLevel": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            }
          ]
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": ["string", "null"]
          }
        },
        "temporal": {
          "$ref": "#/definitions/Temporal"
        },
        "addresses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Address"
          },
          "minItems": 1
        },
        "DCATThemes": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          },
          "minItems": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "periodicity": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            }
          ]
        },
        "legalBasis": {
          "type": ["string", "null"]
        },
        "distributions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Distribution"
          },
          "minItems": 1
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "addresses",
        "DCATThemes",
        "distributions"
      ],
      "title": "BMI"
    },
    "Address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ref": {
          "type": "string"
        },
        "type": {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        }
      },
      "required": ["ref", "type"],
      "title": "Address"
    },
    "Distribution": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "link": {
          "$ref": "#/definitions/Link"
        },
        "title": {
          "type": ["string", "null"]
        },
        "description": {
          "type": ["string", "null"]
        },
        "format": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            }
          ]
        },
        "license": {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        },
        "byClause": {
          "type": ["string", "null"]
        },
        "modified": {
          "type": ["string", "null"]
        },
        "availability": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            }
          ]
        },
        "languages": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        }
      },
      "required": ["link"],
      "title": "Distribution"
    },
    "Link": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "uri": {
          "type": ["string", "null"]
        },
        "value": {
          "type": ["string", "null"]
        },
        "asLink": {
          "type": ["boolean", "null"]
        },
        "lastModified": {
          "type": ["string", "null"]
        }
      },
      "required": ["asLink", "uri", "value"],
      "title": "Link"
    },
    "Event": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "date": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "text": {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        }
      },
      "required": ["date", "text"],
      "title": "Event"
    },
    "Spatial": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "type": "string"
        },
        "ars": {
          "type": ["string", "null"]
        },
        "title": {
          "type": ["string", "null"]
        },
        "value": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/Value"
            }
          ]
        },
        "wkt": {
          "type": ["string", "null"]
        }
      },
      "required": ["type"],
      "title": "Spatial"
    },
    "Value": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "lat1": {
          "type": "number"
        },
        "lat2": {
          "type": "number"
        },
        "lon1": {
          "type": "number"
        },
        "lon2": {
          "type": "number"
        }
      },
      "required": ["lat1", "lat2", "lon1", "lon2"],
      "title": "Value"
    },
    "Temporal": {
      "type": "object",
      "oneOf": [
        {
          "additionalProperties": false,
          "required": ["timeSpanDate"],
          "properties": {
            "rangeType": {
              "oneOf": [
                {
                  "type": "null"
                },
                {
                  "$ref": "../../general.schema.json#/definitions/KeyValue"
                }
              ]
            },
            "timeSpanDate": {
              "type": ["string", "null"],
              "format": "date-time"
            }
          }
        },
        {
          "additionalProperties": false,
          "required": ["timeSpanRange"],
          "properties": {
            "rangeType": {
              "oneOf": [
                {
                  "type": "null"
                },
                {
                  "$ref": "../../general.schema.json#/definitions/KeyValue"
                }
              ]
            },
            "timeSpanRange": {
              "oneOf": [
                {
                  "type": "null"
                },
                {
                  "$ref": "#/definitions/Range"
                }
              ]
            }
          }
        },
        {
          "additionalProperties": false,
          "properties": {
            "rangeType": {
              "type": "null"
            }
          }
        }
      ],
      "required": ["rangeType"],
      "title": "Temporal"
    },
    "Range": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "start": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "end": {
          "type": ["string", "null"],
          "format": "date-time"
        }
      },
      "title": "KeyValue"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/bmi/document_max.json
{
  "_uuid": "cb054900-0205-4847-9d27-1391c07ac149",
  "_type": "OpenDataDoc",
  "title": "Anlagen zur Lagerung und Behandlung von Elektronikschrott (Opendata)",
  "description": "Anlagen zur Lagerung und Behandlung von Elektronikschrott",
  "landingPage": "https://piveau.io/set/data/https-opendata-muenchen-de-dataset-abfall_elektronik_opendata",
  "addresses": [
    {
      "ref": "bb42efb2-ecc8-40b0-bc13-7e7e1cae0342",
      "type": {
        "key": "7"
      }
    },
    {
      "ref": "361312c4-f02d-498d-aa5f-6f146eabae42",
      "type": {
        "key": "12"
      }
    }
  ],
  "keywords": [
    "digitaler-zwilling-münchen",
    "infomapaccessservice",
    "opendata",
    "umweltschutz"
  ],
  "DCATThemes": [
    {
      "key": "5"
    }
  ],
  "distributions": [
    {
      "link": {
        "uri": "https://piveau.io/set/distribution/d2724433-e1f4-405a-9bb8-5563a976e676",
        "value": "https://piveau.io/set/distribution/d2724433-e1f4-405a-9bb8-5563a976e676",
        "asLink": true
      },
      "title": "WMS (GetCapabilities)",
      "format": {
        "key": "WMS_SRVC"
      },
      "license": {
        "key": "http://dcat-ap.de/def/licenses/dl-by-de/2.0"
      },
      "byClause": "",
      "modified": "2024-06-16T22:00:00.000Z",
      "languages": [],
      "description": "",
      "availability": null
    },
    {
      "link": {
        "uri": "https://piveau.io/set/distribution/ffbc1b1e-1e49-4fda-9a43-22caf8bfd869",
        "value": "https://piveau.io/set/distribution/ffbc1b1e-1e49-4fda-9a43-22caf8bfd869",
        "asLink": true
      },
      "title": "Metadaten (XML)",
      "format": {
        "key": "XML"
      },
      "license": {
        "key": "http://dcat-ap.de/def/licenses/dl-by-de/2.0"
      },
      "byClause": "",
      "modified": "2024-06-16T22:00:00.000Z",
      "languages": [],
      "description": "",
      "availability": null
    },
    {
      "link": {
        "uri": "anlagen-zur-lagerung-und-behandlung-von-elektronikschrott-opendata.rdf",
        "value": "anlagen-zur-lagerung-und-behandlung-von-elektronikschrott-opendata.rdf",
        "asLink": false,
        "lastModified": "2024-07-16T14:40:36.508Z"
      },
      "title": "Link zu den Metadaten im Format RDF/XML",
      "format": {
        "key": "RDF"
      },
      "license": {
        "key": "http://dcat-ap.de/def/licenses/dl-by-de/2.0"
      },
      "byClause": "",
      "modified": "2024-06-16T22:00:00.000Z",
      "languages": [],
      "description": "",
      "availability": null
    }
  ],
  "legalBasis": "Rechtsgrundlage",
  "qualityProcessURI": "Quali URI",
  "spatial": [
    {
      "ars": "091620000000",
      "type": "free",
      "title": "München, Bayern, Deutschland (administrative)",
      "value": {
        "lat1": 48.0616244,
        "lat2": 48.2481162,
        "lon1": 11.360777,
        "lon2": 11.7229099
      }
    }
  ],
  "politicalGeocodingLevel": {
    "key": "european"
  },
  "temporal": {
    "rangeType": {
      "key": "at"
    },
    "timeSpanDate": "2024-10-13T22:00:00.000Z"
  },
  "periodicity": {
    "key": "11"
  }
}
