=== informationgrid/ingrid-editor/server/src/main/resources/mcloud/schemes/address.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/definitions/McloudAddress",
  "definitions": {
    "McloudAddress": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_uuid": {
          "type": "string"
        },
        "_type": {
          "type": "string"
        },
        "title": {
          "type": "string",
          "minLength": 1
        },
        "address": {
          "$ref": "../../general.schema.json#/definitions/AddressClass"
        },
        "contact": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Contact"
          },
          "minItems": 1
        },
        "organization": {
          "type": "string"
        }
      },
      "required": ["_uuid", "_type", "organization", "contact"],
      "title": "Address"
    },
    "Contact": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "type": {
          "$ref": "#/definitions/KeyValue"
        },
        "connection": {
          "type": "string"
        }
      },
      "required": ["connection", "type"],
      "title": "Contact"
    },
    "KeyValue": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "key": {
          "type": ["string", "null"]
        },
        "value": {
          "type": ["string", "null"]
        }
      },
      "title": "KeyValue"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/mcloud/mcloud-address.full.json
{
  "title": "Published Testorganization",
  "_uuid": "214ca5bf-da1b-4003-b7b6-e73a2ef0ec10",
  "_type": "McloudAddressDoc",
  "address": {
    "city": "Frankfurt",
    "po-box": "ABCDEF",
    "street": "Musterstr. 12",
    "zip-code": "12345",
    "zip-po-box": "98765"
  },
  "contact": [
    {
      "type": {
        "key": "1"
      },
      "connection": "03351464321653"
    },
    {
      "type": {
        "key": "3"
      },
      "connection": "abc@def.gh"
    }
  ],
  "organization": "Published Testorganization"
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/mcloud/mcloud-address.minimal.json
{
  "title": "Published Testorganization",
  "_uuid": "214ca5bf-da1b-4003-b7b6-e73a2ef0ec10",
  "_type": "McloudAddressDoc",
  "address": {
    "city": null,
    "po-box": null,
    "street": null,
    "zip-code": null,
    "zip-po-box": null
  },
  "contact": [
    {
      "type": {
        "key": "1"
      },
      "connection": "03351464321653"
    }
  ],
  "organization": "Published Testorganization"
}
