=== informationgrid/ingrid-editor/server/src/main/resources/mcloud/schemes/mcloud.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$ref": "#/definitions/MCLOUD",
  "definitions": {
    "MCLOUD": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "_uuid": {
          "type": "string"
        },
        "_type": {
          "type": "string"
        },
        "title": {
          "type": ["string", "null"],
          "minLength": 1
        },
        "events": {
          "type": ["null", "array"],
          "items": {
            "$ref": "#/definitions/Event"
          }
        },
        "origin": {
          "type": ["string", "null"]
        },
        "license": {
          "$ref": "#/definitions/KeyValue"
        },
        "spatial": {
          "type": ["array", "null"],
          "items": {
            "$ref": "#/definitions/Spatial"
          }
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": ["string", "null"]
          }
        },
        "mfundFKZ": {
          "type": ["string", "null"]
        },
        "temporal": {
          "$ref": "#/definitions/Temporal"
        },
        "addresses": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Address"
          },
          "minItems": 1
        },
        "DCATThemes": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "periodicity": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/KeyValue"
            }
          ]
        },
        "accessRights": {
          "type": ["string", "null"]
        },
        "mfundProject": {
          "type": ["string", "null"]
        },
        "distributions": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Distribution"
          },
          "minItems": 1
        },
        "mCloudCategories": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "minItems": 1
        }
      },
      "required": [
        "_uuid",
        "_type",
        "title",
        "description",
        "addresses",
        "mCloudCategories",
        "DCATThemes",
        "distributions",
        "license"
      ],
      "title": "MCLOUD"
    },
    "Address": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "ref": {
          "type": "string"
        },
        "type": {
          "$ref": "#/definitions/KeyValue"
        }
      },
      "required": ["ref", "type"],
      "title": "Address"
    },
    "Distribution": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "link": {
          "$ref": "#/definitions/Link"
        },
        "type": {
          "$ref": "#/definitions/KeyValue"
        },
        "title": {
          "type": ["string", "null"]
        },
        "format": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/KeyValue"
            }
          ]
        }
      },
      "required": ["link", "type"],
      "title": "Distribution"
    },
    "Link": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "uri": {
          "type": ["string", "null"]
        },
        "value": {
          "type": ["string", "null"]
        },
        "asLink": {
          "type": ["boolean", "null"]
        }
      },
      "required": ["asLink", "uri", "value"],
      "title": "Link"
    },
    "Event": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "date": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "text": {
          "$ref": "#/definitions/KeyValue"
        }
      },
      "required": ["date", "text"],
      "title": "Event"
    },
    "Spatial": {
      "type": "object",
      "additionalProperties": true,
      "properties": {
        "type": {
          "type": "string"
        },
        "title": {
          "type": ["string", "null"]
        },
        "value": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/Value"
            }
          ]
        },
        "wkt": {
          "type": ["string", "null"]
        }
      },
      "required": ["title", "type", "value"],
      "title": "Spatial"
    },
    "Value": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "lat1": {
          "type": "number"
        },
        "lat2": {
          "type": "number"
        },
        "lon1": {
          "type": "number"
        },
        "lon2": {
          "type": "number"
        }
      },
      "required": ["lat1", "lat2", "lon1", "lon2"],
      "title": "Value"
    },
    "Temporal": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "rangeType": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/KeyValue"
            }
          ]
        },
        "timeSpanDate": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "timeSpanRange": {
          "oneOf": [
            {
              "type": "null"
            },
            {
              "$ref": "#/definitions/Range"
            }
          ]
        }
      },
      "required": ["rangeType"],
      "title": "Temporal"
    },
    "KeyValue": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "key": {
          "type": ["string", "null"]
        },
        "value": {
          "type": ["string", "null"]
        }
      },
      "title": "KeyValue"
    },
    "Range": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "start": {
          "type": ["string", "null"],
          "format": "date-time"
        },
        "end": {
          "type": ["string", "null"],
          "format": "date-time"
        }
      },
      "title": "KeyValue"
    }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/mcloud/mcloud.full.json
{
  "title": "mCloudDoc1",
  "_uuid": "96b192b6-987e-4f64-8a37-c752f33a4536",
  "_type": "mCloudDoc",
  "description": "Testbeschreibung",
  "addresses": [
    {
      "ref": "214ca5bf-da1b-4003-b7b6-e73a2ef0ec10",
      "type": {
        "key": "10"
      }
    }
  ],
  "keywords": ["eins", "zwei", "drei"],
  "accessRights": "Nutzung",
  "mCloudCategories": ["railway"],
  "DCATThemes": ["TRAN"],
  "distributions": [
    {
      "title": "linkTitel",
      "link": {
        "uri": "https://docs.cypress.io/api/this",
        "value": "https://docs.cypress.io/api/this",
        "asLink": true
      },
      "type": {
        "key": "AtomFeed"
      },
      "format": {
        "key": "CSV"
      }
    }
  ],
  "license": {
    "key": "10"
  },
  "origin": "Meine Quelle",
  "mfundProject": "12345",
  "mfundFKZ": "98765",
  "spatial": [
    {
      "value": {
        "lat1": 50.51342652633956,
        "lon1": 8.613281250000002,
        "lat2": 53.22576843579022,
        "lon2": 13.0078125
      },
      "title": "Neuer Raumbezug",
      "type": "free"
    }
  ],
  "events": [
    {
      "date": "2022-01-31T23:00:00.000Z",
      "text": {
        "key": "1"
      }
    },
    {
      "date": "2022-03-15T23:00:00.000Z",
      "text": {
        "key": "3"
      }
    }
  ],
  "temporal": {
    "rangeType": {
      "key": "at"
    },
    "timeSpanDate": "2022-02-07T23:00:00.000Z"
  },
  "periodicity": {
    "key": "10"
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/mcloud/mcloud.json
{
  "DCATThemes": [
    "TRAN",
    "REGI"
  ],
  "_type": "mCloudDoc",
  "_uuid": "1583881f-45c3-4105-b081-e33f19ce0b1e",
  "accessRights": null,
  "addresses": [
    {
      "ref": "0B2B815A-4E9D-4F47-8286-B2DE17CB874F",
      "type": {
        "key": "10"
      }
    }
  ],
  "description": "Sensordaten (ohne GPS-Signal) des ECOSense-Projekts. Der Datensatz setzt sich zusammen aus Sensordaten, die im 1 Hz-Bereich und 24 Hz-Bereich gemessen wurden. \n\nGesamtvolumen: 14859 Fahrten / 3,74 GB (komprimiert) / 36,2 GB (entpackt)\n\n\nFolgende Daten sind enthalten: \n- internal_index \n- 1Hz-Bereich: measured_date, estimated_date, longitude, latitude, speed, heading, certainty, temperature1, temperature2, humidity, pressure, altitude2\n- 24Hz-Bereich: Beschleunigung in drei Achsen (accel_x_01-24, accel_y_01-24, accel_z_01-24), Gyroskop in drei Achsen (gyro_x_01-24, gyro_y_01-24, gyro_z_01-24), Magnetometer in drei Achsen (mag_x_01-24, mag_y_01-24, mag_z_01-24). \n",
  "distributions": [
    {
      "link": {
        "uri": "https://ecosense01.vlba.uni-oldenburg.de/data/2020-mcloud-ecosense-data-export-nogps-1.7z",
        "value": "https://ecosense01.vlba.uni-oldenburg.de/data/2020-mcloud-ecosense-data-export-nogps-1.7z",
        "asLink": true
      },
      "type": {
        "key": "download"
      },
      "title": "Sensordaten (ohne GPS) - 1",
      "format": {
        "key": "CSV"
      }
    },
    {
      "link": {
        "uri": "https://ecosense01.vlba.uni-oldenburg.de/data/2020-mcloud-ecosense-data-export-nogps-2.7z",
        "value": "https://ecosense01.vlba.uni-oldenburg.de/data/2020-mcloud-ecosense-data-export-nogps-2.7z",
        "asLink": true
      },
      "type": {
        "key": "atomFeed"
      },
      "title": "Sensordaten (ohne GPS) - 2",
      "format": {
        "key": "SVG"
      }
    },
    {
      "link": {
        "uri": "https://ecosense01.vlba.uni-oldenburg.de/data/2020-mcloud-ecosense-data-export-nogps-3.7z",
        "value": "https://ecosense01.vlba.uni-oldenburg.de/data/2020-mcloud-ecosense-data-export-nogps-3.7z",
        "asLink": true
      },
      "type": {
        "key": "wms"
      },
      "title": "Sensordaten (ohne GPS) - 3",
      "format": {
        "key": "MAP_SRVC"
      }
    }
  ],
  "events": [
    {
      "date": "2020-11-22T23:00:00.000Z",
      "text": {
        "key": "1"
      }
    }
  ],
  "keywords": [],
  "license": {
    "key": "28"
  },
  "mCloudCategories": [
    "infrastructure",
    "roads"
  ],
  "mfundFKZ": "VB18F1030A",
  "mfundProject": "ECOSense",
  "origin": "Quelle: Projekt ECOSense (mein-dienstrad.de, Universit√§t Oldenburg/Abteilung Wirtschaftsinformatik (VLBA), CoSynth)",
  "periodicity": {},
  "spatial": [
    {
      "type": "free",
      "title": "Bundesrepublik Deutschland",
      "value": {
        "lat1": 47.23942,
        "lat2": 55.054344,
        "lon1": 6.098034,
        "lon2": 15.578555
      }
    },
    {
      "wkt": "POLYGON((7.9891204833984375 53.22247975316637,7.989807128906249 53.06556366279212,8.368148803710938 53.066801462406524,8.368148803710938 53.22330194749886,7.9891204833984375 53.22247975316637))",
      "type": "wkt",
      "title": "WKT Raumbezug",
      "value": null
    }
  ],
  "temporal": {
    "rangeType": {
      "key": "range"
    },
    "timeSpanRange": {
      "end": "2020-04-29T22:00:00.000Z",
      "start": "2019-10-31T23:00:00.000Z"
    }
  },
  "title": "Test Doc"
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/mcloud/mcloud.minimal.json
{
  "DCATThemes": [
    "TRAN",
    "REGI"
  ],
  "_type": "mCloudDoc",
  "_uuid": "1583881f-45c3-4105-b081-e33f19ce0b1e",
  "accessRights": null,
  "addresses": [
    {
      "ref": "0B2B815A-4E9D-4F47-8286-B2DE17CB874F",
      "type": {
        "key": "10"
      }
    }
  ],
  "description": "Sensordaten (ohne GPS-Signal) des ECOSense-Projekts. Der Datensatz setzt sich zusammen aus Sensordaten, die im 1 Hz-Bereich und 24 Hz-Bereich gemessen wurden. \n\nGesamtvolumen: 14859 Fahrten / 3,74 GB (komprimiert) / 36,2 GB (entpackt)\n\n\nFolgende Daten sind enthalten: \n- internal_index \n- 1Hz-Bereich: measured_date, estimated_date, longitude, latitude, speed, heading, certainty, temperature1, temperature2, humidity, pressure, altitude2\n- 24Hz-Bereich: Beschleunigung in drei Achsen (accel_x_01-24, accel_y_01-24, accel_z_01-24), Gyroskop in drei Achsen (gyro_x_01-24, gyro_y_01-24, gyro_z_01-24), Magnetometer in drei Achsen (mag_x_01-24, mag_y_01-24, mag_z_01-24). \n",
  "distributions": [
    {
      "link": {
        "uri": "https://ecosense01.vlba.uni-oldenburg.de/data/2020-mcloud-ecosense-data-export-nogps-1.7z",
        "value": "https://ecosense01.vlba.uni-oldenburg.de/data/2020-mcloud-ecosense-data-export-nogps-1.7z",
        "asLink": true
      },
      "type": {
        "key": "download"
      }
    }
  ],
  "events": null,
  "keywords": [],
  "license": {
    "key": "28"
  },
  "mCloudCategories": [
    "infrastructure",
    "roads"
  ],
  "mfundFKZ": null,
  "mfundProject": null,
  "origin": null,
  "periodicity": null,
  "spatial": null,
  "temporal": {
    "rangeType": null,
    "timeSpanRange": null
  },
  "title": "Test Doc"
}
