=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/algorithm-base.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://wemove.com/schemas/ingrid/schemes/algorithmBase",
  "type": "object",
  "definitions": {
    "propertiesAlgorithm": {
      "type": "object",
      "properties": {
        "isAdVCompatible": {
          "type": ["null", "boolean"]
        },
        "isOpenData": {
          "type": ["null", "boolean"]
        },
        "isInspireIdentified": {
          "type": ["null", "string"]
        }
      }
    },
    "inputOutputData": {
      "type": "array",
      "items": {
        "type": "object",
        "unevaluatedProperties": false,
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": ["null", "string"]
          },
          "attributes": {
            "type": ["null", "array"],
            "items": {
              "type": "object",
              "unevaluatedProperties": false,
              "properties": {
                "name": {
                  "type": "string"
                },
                "unit": {
                  "type": ["null", "string"]
                },
                "spatialResolution": {
                  "type": ["null", "string"]
                },
                "temporalResolution": {
                  "type": ["null", "string"]
                }
              }
            }
          }
        },
        "required": ["name"]
      }
    },
    "additionalUrls": {
      "type": "array",
      "items": {
        "type": "object",
        "unevaluatedProperties": false,
        "properties": {
          "name": {
            "type": "string"
          },
          "url": {
            "type": ["null", "string"]
          }
        },
        "required": ["name", "url"]
      }
    }
  },
  "properties": {
    "properties": {
      "$ref": "#/definitions/propertiesAlgorithm"
    },
    "_uuid": {
      "type": "string"
    },
    "_type": {
      "const": "InGridAlgorithm"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "alternateTitle": {
      "type": ["null", "string"]
    },
    "parentIdentifier": {
      "type": ["null", "string"]
    },
    "pointOfContact": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/PointOfContact"
      },
      "minItems": 1
    },
    "trainingData": {
      "type": ["null", "string"]
    },
    "dataBias": {
      "type": ["null", "string"]
    },
    "inputData": {
      "$ref": "#/definitions/inputOutputData"
    },
    "outputData": {
      "$ref": "#/definitions/inputOutputData"
    },
    "algorithmType": {
      "type": ["null", "string"]
    },
    "explanation": {
      "type": ["null", "string"]
    },
    "methods": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "errorBias": {
      "type": ["null", "string"]
    },
    "monitoring": {
      "type": ["null", "string"]
    },
    "typeOfUse": {
      "type": ["null", "string"]
    },
    "apiUrl": {
      "type": ["null", "string"]
    },
    "sourceCodeUrl": {
      "type": ["null", "string"]
    },
    "websiteUrl": {
      "type": ["null", "string"]
    },
    "exampleUrl": {
      "type": ["null", "string"]
    },
    "publiccodeUrl": {
      "type": ["null", "string"]
    },
    "additionalUrls": {
      "$ref": "#/definitions/additionalUrls"
    },
    "themes": {
      "$ref": "refs/general.schema.json#/definitions/themes"
    },
    "keywords": {
      "$ref": "refs/general.schema.json#/definitions/keywords"
    },
    "spatial": {
      "$ref": "refs/general.schema.json#/definitions/Spatial"
    },
    "temporal": {
      "$ref": "refs/general.schema.json#/definitions/temporal"
    },
    "dataset": {
      "$ref": "refs/general.schema.json#/definitions/dataset"
    },
    "extraInfo": {
      "$ref": "refs/general.schema.json#/definitions/extraInfo"
    },
    "metadata": {
      "$ref": "refs/general.schema.json#/definitions/metadata"
    },
    "resource": {
      "$ref": "refs/general.schema.json#/definitions/resource"
    },
    "maintenanceInformation": {
      "$ref": "refs/general.schema.json#/definitions/maintenanceInformation"
    },
    "orderInfo": {
      "$ref": "refs/general.schema.json#/definitions/orderInfo"
    },
    "distribution": {
      "$ref": "refs/general.schema.json#/definitions/distribution"
    },
    "digitalTransferOptions": {
      "$ref": "refs/general.schema.json#/definitions/digitalTransferOptions"
    },
    "openDataCategories": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "fileReferences": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/FileReference"
      }
    }
  },
  "required": [
    "_uuid",
    "_type",
    "title",
    "description",
    "pointOfContact",
    "spatial",
    "temporal",
    "metadata",
    "dataset"
  ],
  "title": "Algorithm"
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/algorithm.minimal.json
{
  "_uuid": "d967e83f-5336-4207-960c-3a6a900d0211",
  "_type": "InGridAlgorithm",
  "title": "aba",
  "properties": { "isOpenData": null },
  "dataset": { "languages": ["142"] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Auma, Auma-Weidatal, Greiz, Thüringen, 07955, Deutschland (town)",
        "value": {
          "lat1": 50.6587079,
          "lat2": 50.7387079,
          "lon1": 11.8593229,
          "lon2": 11.9393229
        }
      }
    ],
    "spatialSystems": [{ "key": "9000001" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": { "free": [] },
  "metadata": { "language": { "key": "150" } },
  "resource": { "useConstraints": [], "accessConstraints": [] },
  "temporal": {
    "event": {
      "created": "2020-12-11T23:00:00.000Z"
    },
    "status": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "description": "some description",
  "pointOfContact": [
    { "ref": "826cd85e-9b65-43f6-b2a7-3f20b57450f4", "type": { "key": "11" } },
    { "ref": "506677eb-9328-4484-9d30-2cecadba353c", "type": { "key": "10" } }
  ],
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  },
  "trainingData": "some training data",
  "dataBias": null,
  "inputData": [
    {
      "name": "some input dataset",
      "url": "https://example.org/input",
      "attributes": [
        {
          "name": "some attribute",
          "unit": "m",
          "spatialResolution": null,
          "temporalResolution": null
        }
      ]
    }
  ],
  "outputData": [
    { "name": "some output dataset", "url": null, "attributes": [] }
  ],
  "algorithmType": "rule-based",
  "explanation": "some explanation",
  "methods": ["some method"],
  "errorBias": null,
  "monitoring": "some monitoring",
  "typeOfUse": "descriptive",
  "apiUrl": null,
  "sourceCodeUrl": null,
  "websiteUrl": null,
  "exampleUrl": null,
  "publiccodeUrl": null,
  "additionalUrls": [{ "name": "example", "url": "https://example.org" }]
}
