=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/geo-dataset-base.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://wemove.com/schemas/ingrid/schemes/geoDatasetBase",
  "definitions": {
    "coupledResources": {
      "type": "array",
      "items": {
        "type": "object",
        "unevaluatedProperties": false,
        "properties": {
          "icon": {
            "type": "string"
          },
          "type": {
            "type": "string"
          },
          "uuid": {
            "type": "string"
          },
          "state": {
            "type": "string"
          },
          "isExternalRef": {
            "type": "boolean"
          }
        }
      }
    },
    "citation": {
      "type": "array",
      "items": {
        "type": "object",
        "unevaluatedProperties": false,
        "properties": {
          "date": {
            "type": "string",
            "format": "date-string"
          },
          "title": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          },
          "edition": {
            "type": ["null", "string"]
          }
        }
      }
    },
    "spatialGrid": {
      "type": ["null", "object"],
      "unevaluatedProperties": false,
      "properties": {
        "type": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        },
        "axesDimensionProperties": {
          "type": "array",
          "items": {
            "properties": {
              "name": {
                "$ref": "../../general.schema.json#/definitions/KeyValue"
              },
              "size": {
                "type": ["null", "number"]
              },
              "resolution": {
                "type": ["null", "number"]
              }
            }
          }
        },
        "transformationParameterAvailability": {
          "type": "boolean"
        },
        "numberOfDimensions": {
          "type": ["null", "number"]
        },
        "cellGeometry": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        },
        "georectified": {
          "type": "object",
          "properties": {
            "checkPointAvailability": {
              "type": "boolean"
            },
            "checkPointDescription": {
              "type": "string"
            },
            "cornerPoints": {
              "type": [
                "null",
                "number"
              ]
            },
            "pointInPixel": {
              "anyOf": [
                {
                  "$ref": "../../general.schema.json#/definitions/KeyValue"
                },
                {
                  "type": "null"
                }
              ]
            }
          }
        },
        "georeferenceable": {
          "type": "object",
          "properties": {
            "orientationParameterAvailability": {
              "type": "boolean"
            },
            "controlPointAvaliability": {
              "type": "boolean"
            }
          }
        }
      }
    },
    "dataQualitySource": {
      "type": "object",
      "properties": {
        "processStep": {
          "type": "object",
          "unevaluatedProperties": false,
          "properties": {
            "description": {
              "type": "array",
              "items": {
                "$ref": "../../general.schema.json#/definitions/KeyValue"
              }
            }
          }
        },
        "descriptions": {
          "type": "array",
          "items": {
            "type": "object",
            "unevaluatedProperties": false,
            "properties": {
              "_type": {
                "type": "string"
              },
              "value": {
                "type": "string"
              },
              "uuidRef": {
                "type": ["null", "string"]
              },
              "url": {
                "type": ["null", "string"]
              },
              "identifier": {
                "type": ["null", "string"]
              },
              "title": {
                "type": ["null", "string"]
              },
              "date": {
                "type": ["null", "string"],
                "format": "date-time"
              },
              "dateType": {
                "anyOf": [
                  {
                    "$ref": "../../general.schema.json#/definitions/KeyValue"
                  },
                  {
                    "type": "null"
                  }
                ]
              }
            }
          }
        }
      }
    },
    "featureDescription": {
      "properties": {
        "citation": {
          "$ref": "#/definitions/citation"
        },
        "featureTypes": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        }
      }
    },
    "propertiesGeoDataset": {
      "type": "object",
      "properties": {
        "isAdVCompatible": {
          "type": ["null", "boolean"]
        },
        "isHvd": {
          "type": ["null", "boolean"]
        },
        "isOpenData": {
          "type": ["null", "boolean"]
        },
        "isInspireIdentified": {
          "type": ["null", "string"]
        },
        "subType": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        },
        "invekos": {
          "type": "object",
          "properties": {
            "type": {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            }
          }
        }
      }
    }
  },
  "type": "object",
  "properties": {
    "properties": {
      "$ref": "#/definitions/propertiesGeoDataset"
    },
    "identifier": {
      "type": "string"
    },
    "spatialRepresentationType": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "vectorSpatialRepresentation": {
      "type": "array",
      "items": {
        "type": "object",
        "unevaluatedProperties": false,
        "properties": {
          "topologyLevel": {
            "anyOf": [
              {
                "$ref": "../../general.schema.json#/definitions/KeyValue"
              },
              {
                "type": "null"
              }
            ]
          },
          "geometricObjectType": {
            "anyOf": [
              {
                "$ref": "../../general.schema.json#/definitions/KeyValue"
              },
              {
                "type": "null"
              }
            ]
          },
          "geometricObjectCount": {
            "type": [
              "null",
              "number"
            ]
          }
        }
      }
    },
    "topicCategories": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "_uuid": {
      "type": "string"
    },
    "_type": {
      "const": "InGridGeoDataset"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "alternateTitle": {
      "type": ["null", "string"]
    },
    "parentIdentifier": {
      "type": ["null", "string"]
    },
    "pointOfContact": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/PointOfContact"
      },
      "minItems": 1
    },
    "publication": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "doi": {
          "type": ["null", "string"]
        },
        "generalResourceType": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        },
        "resourceType": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        }
      }
    },
    "advProductGroups": {
      "$ref": "refs/general.schema.json#/definitions/advProductGroups"
    },
    "themes": {
      "$ref": "refs/general.schema.json#/definitions/themes"
    },
    "spatial": {
      "$ref": "refs/general.schema.json#/definitions/Spatial"
    },
    "temporal": {
      "$ref": "refs/general.schema.json#/definitions/temporal"
    },
    "resolution": {
      "$ref": "refs/general.schema.json#/definitions/resolution"
    },
    "lineage": {
      "type": "object",
      "unevaluatedProperties": false,
      "properties": {
        "statement": {
          "type": "string"
        }
      }
    },
    "qualities": {
      "type": "array",
      "items": {
        "type": "object",
        "unevaluatedProperties": false,
        "properties": {
          "_type": {
            "type": "string"
          },
          "value": {
            "type": ["null", "number"]
          },
          "parameter": {
            "type": ["null", "string"]
          },
          "measureType": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        }
      }
    },
    "portrayalCatalogueInfo": {
      "type": "object",
      "unevaluatedProperties": false,
      "properties": {
        "citation": {
          "$ref": "#/definitions/citation"
        }
      }
    },
    "featureCatalogueDescription": {
      "$ref": "#/definitions/featureDescription"
    },
    "extraInfo": {
      "$ref": "refs/general.schema.json#/definitions/extraInfo"
    },
    "metadata": {
      "$ref": "refs/general.schema.json#/definitions/metadata"
    },
    "resource": {
      "$ref": "refs/general.schema.json#/definitions/resource"
    },
    "keywords": {
      "$ref": "refs/general.schema.json#/definitions/keywords"
    },
    "digitalTransferOptions": {
      "$ref": "refs/general.schema.json#/definitions/digitalTransferOptions"
    },
    "distribution": {
      "$ref": "refs/general.schema.json#/definitions/distribution"
    },
    "dataset": {
      "$ref": "refs/general.schema.json#/definitions/dataset"
    },
    "dataQuality": {
      "type": "object",
      "unevaluatedProperties": false,
      "properties": {
        "completenessOmission": {
          "type": "object",
          "unevaluatedProperties": false,
          "properties": {
            "measResult": {
              "type": ["null", "number"]
            }
          }
        }
      }
    },
    "dataQualityInfo": {
      "type": "object",
      "unevaluatedProperties": false,
      "properties": {
        "lineage": {
          "type": "object",
          "unevaluatedProperties": false,
          "properties": {
            "source": {
              "$ref": "#/definitions/dataQualitySource"
            }
          }
        }
      }
    },
    "absoluteExternalPositionalAccuracy": {
      "type": "object",
      "unevaluatedProperties": false,
      "properties": {
        "vertical": {
          "type": ["null", "number"]
        },
        "horizontal": {
          "type": ["null", "number"]
        },
        "griddedDataPositionalAccuracy": {
          "type": ["null", "number"]
        }
      }
    },
    "priorityDatasets": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "invekosKeywords": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "hvd": {
      "type": ["null", "boolean"]
    },
    "hvdCategories": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "spatialScope": {
      "anyOf": [
        {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        },
        {
          "type": "null"
        }
      ]
    },
    "maintenanceInformation": {
      "$ref": "refs/general.schema.json#/definitions/maintenanceInformation"
    },
    "references": {
      "$ref": "refs/general.schema.json#/definitions/references"
    },
    "graphicOverviews": {
      "$ref": "refs/general.schema.json#/definitions/graphicOverviews"
    },
    "orderInfo": {
      "$ref": "refs/general.schema.json#/definitions/orderInfo"
    },
    "service": {
      "type": "object",
      "unevaluatedProperties": false,
      "properties": {
        "type": {
          "$ref": "../../general.schema.json#/definitions/KeyValue"
        },
        "version": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        },
        "operations": {
          "type": "array",
          "items": {
            "type": "object",
            "unevaluatedProperties": false,
            "properties": {
              "name": {
                "type": "string"
              },
              "methodCall": {
                "type": "string"
              },
              "description": {
                "type": ["null", "string"]
              }
            }
          }
        },
        "resolution": {
          "$ref": "refs/general.schema.json#/definitions/resolution"
        },
        "explanation": {
          "type": ["null", "string"]
        },
        "couplingType": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        },
        "classification": {
          "type": "array",
          "items": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          }
        },
        "coupledResources": {
          "$ref": "#/definitions/coupledResources"
        },
        "systemEnvironment": {
          "type": ["null", "string"]
        },
        "hasAccessConstraints": {
          "type": ["null", "boolean"]
        },
        "implementationHistory": {
          "type": ["null", "string"]
        }
      }
    },
    "conformanceResult": {
      "type": "array",
      "items": {
        "type": "object",
        "unevaluatedProperties": false,
        "properties": {
          "pass": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          },
          "isInspire": {
            "type": ["null", "boolean"]
          },
          "explanation": {
            "type": ["null", "string"]
          },
          "specification": {
            "$ref": "../../general.schema.json#/definitions/KeyValue"
          },
          "publicationDate": {
            "type": "string"
          }
        }
      }
    },
    "gridSpatialRepresentation": {
      "$ref": "#/definitions/spatialGrid"
    },
    "openDataCategories": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "fileReferences": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/FileReference"
      }
    }
  },
  "required": [
    "_uuid",
    "_type",
    "title",
    "topicCategories",
    "lineage",
    "description",
    "pointOfContact",
    "spatial",
    "temporal",
    "metadata",
    "dataset",
    "resource"
  ],
  "title": "GeoDataset"
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/geo-dataset.maximal.json
{
  "_uuid": "5369ad60-938f-4325-b041-25dacfc14709",
  "title": "geodataset-test",
  "_type": "InGridGeoDataset",
  "properties": {
    "isOpenData": false,
    "isAdVCompatible": true,
    "subType": { "key": "5" }
  },
  "openDataCategories": [
    {
      "key": "9",
      "value": "Bevölkerung und Gesellschaft",
      "_codelistId": "6400"
    }
  ],
  "themes": [{ "key": "317" }],
  "dataset": { "languages": ["134"] },
  "lineage": { "statement": "basis" },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Linda, Neustadt an der Orla, Saale-Orla-Kreis, Thüringen, Deutschland (administrative)",
        "value": {
          "lat1": 50.6638647,
          "lat2": 50.7090902,
          "lon1": 11.7449969,
          "lon2": 11.8477633
        }
      },
      {
        "type": "free",
        "ars": "1389283743"
      }
    ],
    "description": "erlaeuterung",
    "spatialSystems": [{ "key": "9000005" }],
    "verticalExtent": {
      "spatialSystem": { "key": "900005" },
      "maximumValue": 6,
      "minimumValue": 7,
      "unitOfMeasure": { "key": "4" }
    }
  },
  "keywords": {
    "free": [{ "label": "optional" }]
  },
  "metadata": { "language": { "key": "103" }, "characterSet": null },
  "resource": {
    "purpose": "production purpose",
    "specificUsage": "aptitude/use",
    "useLimitation": "use constraints",
    "useConstraints": [
      { "title": { "key": "17" }, "source": "terms of use source" }
    ],
    "accessConstraints": [{ "key": "6" }]
  },
  "temporal": {
    "event": {
      "lastModified": "2022-01-12T23:00:00.000Z"
    },
    "status": { "key": "2" },
    "data": {
      "type": "range",
      "resourceDate": "2020-09-03T22:00:00.000Z",
      "intervalFrom": "date",
      "intervalTo": "not-available"
    }
  },
  "extraInfo": { "legalBasicsDescriptions": [{ "key": "59" }] },
  "orderInfo": "bestellinfo",
  "qualities": [
    {
      "_type": "domainConsistency",
      "value": 2,
      "parameter": "param",
      "measureType": { "key": "1" }
    }
  ],
  "identifier": "identifier of data source",
  "references": [
    {
      "url": "data-download.com",
      "referenceType": "url",
      "type": { "key": "9990" },
      "title": "data download",
      "explanation": "more-info"
    }
  ],
  "resolution": [{ "denominator": 4, "distanceDPI": 1, "distanceMeter": 6 }],
  "dataQuality": { "completenessOmission": { "measResult": 55 } },
  "description": "description",
  "distribution": {},
  "spatialScope": { "key": "885989663" },
  "alternateTitle": "short description",
  "pointOfContact": [
    { "ref": "83f92167-6606-4182-948c-5747ad608b80", "type": { "key": "11" } },
    { "ref": "dcf24d5c-7a33-4ffa-8f27-5f47af964a73", "type": { "key": "7" } }
  ],
  "dataQualityInfo": {
    "lineage": {
      "source": {
        "processStep": {
          "description": [
            {
              "key": null,
              "value": "production process"
            }
          ]
        },
        "descriptions": [
          {
            "_type": "freeDescription",
            "value": "Ein freier Beschreibungstext"
          },
          {
            "_type": "freeDescription",
            "value": "Beschreibungstext",
            "identifier": "https://registry.gdi-de.org/id/ogctestcatalog/e8f0fcbb-3583-4848-9782-d2e89dcba887",
            "title": "Titel von Referenz",
            "date": "2024-09-02T22:00:00.000Z",
            "dateType": {
              "key": "2"
            }
          },
          {
            "_type": "internalDataOrigin",
            "value": "Lokale interne Referenz",
            "uuidRef": "4915275a-733a-47cd-b1a6-1a3f1e976948",
            "date": "2025-02-26T23:00:00.000Z",
            "dateType": {
              "key": "3"
            }
          }
        ]
      }
    }
  },
  "topicCategories": [{ "key": "2" }],
  "advProductGroups": [{ "key": "13" }],
  "graphicOverviews": [
    {
      "title": "first_archived",
      "fileName": {
        "uri": "first_archived.txt",
        "value": "first_archived.txt",
        "asLink": false
      }
    }
  ],
  "parentIdentifier": "identifier",
  "priorityDatasets": [{ "key": "-79614265" }],
  "conformanceResult": [
    {
      "pass": { "key": "1" },
      "isInspire": true,
      "explanation": "etwas",
      "specification": { "key": "11" },
      "publicationDate": "2009-12-15"
    }
  ],
  "digitalTransferOptions": [
    {
      "name": { "key": "900006" },
      "mediumNote": "speicherort",
      "transferSize": { "value": 100, "unit": { "key": "MB" } }
    }
  ],
  "maintenanceInformation": {
    "description": "mehr erläuterungen",
    "maintenanceAndUpdateFrequency": { "key": "1" },
    "userDefinedMaintenanceFrequency": { "unit": { "key": "6" }, "number": 6 }
  },
  "portrayalCatalogueInfo": {
    "citation": [
      {
        "date": "2021-10-06T22:00:00.000Z",
        "title": { "key": "1" },
        "edition": "6"
      }
    ]
  },
  "spatialRepresentationType": [{ "key": "1" }],
  "featureCatalogueDescription": {
    "citation": [
      {
        "date": "2022-04-06T22:00:00.000Z",
        "title": { "key": "1" },
        "edition": "9"
      }
    ],
    "featureTypes": [{ "key": null, "value": "attribute info" }]
  },
  "vectorSpatialRepresentation": [
    {
      "topologyLevel": { "key": "4" },
      "geometricObjectType": { "key": "6" },
      "geometricObjectCount": 2
    }
  ],
  "absoluteExternalPositionalAccuracy": { "vertical": 5, "horizontal": 3 },
  "publication": {
    "doi": "10.1000/1234",
    "generalResourceType": { "key": "5" },
    "resourceType": { "key": "2" }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/geo-dataset.minimal.json
{
  "_uuid": "5369ad60-938f-4325-b041-25dacfc14705",
  "title": "geodataset_min",
  "_type": "InGridGeoDataset",
  "properties": {
    "isOpenData": false,
    "isAdVCompatible": false,
    "subType": { "key": "5" }
  },
  "themes": [],
  "dataset": { "languages": [] },
  "lineage": { "statement": "basics" },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Pleißa, Limbach-Oberfrohna, Zwickau, Sachsen, 09212, Deutschland (village)",
        "value": {
          "lat1": 50.8119735,
          "lat2": 50.8519735,
          "lon1": 12.738966,
          "lon2": 12.778966
        }
      }
    ],
    "spatialSystems": [{ "key": "25833" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": {
    "free": []
  },
  "metadata": { "language": { "key": "306" }, "characterSet": null },
  "resource": {
    "useConstraints": [{ "title": { "key": "22" }, "source": "source4" }],
    "accessConstraints": []
  },
  "temporal": {
    "event": {
      "lastModified": "2021-12-08T23:00:00.000Z"
    },
    "status": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "qualities": [],
  "identifier": "identifier",
  "references": [],
  "resolution": [],
  "dataQuality": { "completenessOmission": {} },
  "description": "description2",
  "distribution": {},
  "spatialScope": null,
  "pointOfContact": [
    { "ref": "826cd85e-9b65-43f6-b2a7-3f20b57450f4", "type": { "key": "11" } },
    { "ref": "506677eb-9328-4484-9d30-2cecadba353c", "type": { "key": "10" } }
  ],
  "dataQualityInfo": {
    "lineage": { "source": { "processStep": {}, "descriptions": [] } }
  },
  "topicCategories": [{ "key": "7" }],
  "advProductGroups": [],
  "priorityDatasets": [],
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  },
  "portrayalCatalogueInfo": { "citation": [] },
  "spatialRepresentationType": [],
  "featureCatalogueDescription": { "citation": [], "featureTypes": [] },
  "absoluteExternalPositionalAccuracy": {}
}
