=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/project-base.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://wemove.com/schemas/ingrid/schemes/projectBase",
  "type": "object",
  "properties": {
    "_uuid": {
      "type": "string"
    },
    "_type": {
      "const": "InGridProject"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "alternateTitle": {
      "type": ["null", "string"]
    },
    "manager": {
      "type": ["null", "string"]
    },
    "participants": {
      "type": ["null", "string"]
    },
    "serviceType": {
      "anyOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "key": {
              "type": "string"
            }
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "serviceUrls": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "url": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      }
    },
    "serviceVersion": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "parentIdentifier": {
      "type": ["null", "string"]
    },
    "pointOfContact": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/PointOfContact"
      },
      "minItems": 1
    },
    "themes": {
      "$ref": "refs/general.schema.json#/definitions/themes"
    },
    "spatial": {
      "$ref": "refs/general.schema.json#/definitions/Spatial"
    },
    "temporal": {
      "$ref": "refs/general.schema.json#/definitions/temporal"
    },
    "dataset": {
      "$ref": "refs/general.schema.json#/definitions/dataset"
    },
    "extraInfo": {
      "$ref": "refs/general.schema.json#/definitions/extraInfo"
    },
    "metadata": {
      "$ref": "refs/general.schema.json#/definitions/metadata"
    },
    "resource": {
      "$ref": "refs/general.schema.json#/definitions/resource"
    },
    "distribution": {
      "$ref": "refs/general.schema.json#/definitions/distribution"
    },
    "keywords": {
      "$ref": "refs/general.schema.json#/definitions/keywords"
    },
    "maintenanceInformation": {
      "$ref": "refs/general.schema.json#/definitions/maintenanceInformation"
    },
    "references": {
      "$ref": "refs/general.schema.json#/definitions/references"
    },
    "graphicOverviews": {
      "$ref": "refs/general.schema.json#/definitions/graphicOverviews"
    },
    "digitalTransferOptions": {
      "$ref": "refs/general.schema.json#/definitions/digitalTransferOptions"
    },
    "categoryCatalog": {
      "$ref": "refs/general.schema.json#/definitions/categoryCatalog"
    },
    "databaseContent": {
      "$ref": "refs/general.schema.json#/definitions/databaseContent"
    },
    "explanation": {
      "$ref": "refs/general.schema.json#/definitions/explanation"
    },
    "methodText": {
      "$ref": "refs/general.schema.json#/definitions/methodText"
    },
    "orderInfo": {
      "$ref": "refs/general.schema.json#/definitions/orderInfo"
    }
  },
  "required": [
    "_uuid",
    "_type",
    "title",
    "description",
    "pointOfContact",
    "spatial",
    "temporal",
    "metadata"
  ],
  "title": "Project"
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/project.minimal.json
{
  "_uuid": "39ebf57c-9b98-4861-804b-0af30ffdb6c0",
  "title": "project_1",
  "_type": "InGridProject",
  "dataset": { "languages": [] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Kahla, Saale-Holzland-Kreis, Thüringen, 07768, Deutschland (administrative)",
        "value": {
          "lat1": 50.7883836,
          "lat2": 50.8255522,
          "lon1": 11.5588954,
          "lon2": 11.6105771
        }
      }
    ],
    "spatialSystems": [{ "key": "9000012" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": {
    "free": []
  },
  "metadata": { "language": { "key": "134" } },
  "resource": { "useConstraints": [], "accessConstraints": [] },
  "temporal": {
    "event": {
      "firstPublished": "2020-10-12T22:00:00.000Z"
    },
    "status": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "references": [],
  "description": "some random description",
  "pointOfContact": [
    { "ref": "826cd85e-9b65-43f6-b2a7-3f20b57450f4", "type": { "key": "7" } }
  ],
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  }
}
