=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/publication-base.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://wemove.com/schemas/ingrid/schemes/publicationBase",
  "type": "object",
  "definitions": {
    "propertiesPublication": {
      "type": "object",
      "properties": {
        "isOpenData": {
          "type": ["null", "boolean"]
        }
      }
    }
  },
  "properties": {
    "properties": {
      "$ref": "#/definitions/propertiesPublication"
    },
    "_uuid": {
      "type": "string"
    },
    "_type": {
      "const": "InGridPublication"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "alternateTitle": {
      "type": ["null", "string"]
    },
    "serviceType": {
      "anyOf": [
        {
          "type": "object",
          "additionalProperties": false,
          "properties": {
            "key": {
              "type": "string"
            }
          }
        },
        {
          "type": "null"
        }
      ]
    },
    "serviceUrls": {
      "type": "array",
      "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
          "url": {
            "type": "string"
          },
          "name": {
            "type": "string"
          },
          "description": {
            "type": "string"
          }
        }
      }
    },
    "serviceVersion": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    },
    "parentIdentifier": {
      "type": ["null", "string"]
    },
    "pointOfContact": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/PointOfContact"
      },
      "minItems": 1
    },
    "publication": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "isbn": {
          "type": ["null", "string"]
        },
        "pages": {
          "type": ["null", "string"]
        },
        "author": {
          "type": ["null", "string"]
        },
        "volume": {
          "type": ["null", "string"]
        },
        "location": {
          "type": ["null", "string"]
        },
        "publisher": {
          "type": ["null", "string"]
        },
        "explanation": {
          "type": ["null", "string"]
        },
        "publishedIn": {
          "type": ["null", "string"]
        },
        "baseDataText": {
          "type": ["null", "string"]
        },
        "doi": {
          "type": ["null", "string"]
        },
        "generalResourceType": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        },
        "resourceType": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        },
        "documentType": {
          "anyOf": [
            {
              "$ref": "../../general.schema.json#/definitions/KeyValue"
            },
            {
              "type": "null"
            }
          ]
        },
        "publicationDate": {
          "type": ["null", "string"]
        },
        "publishingHouse": {
          "type": ["null", "string"]
        },
        "bibliographicData": {
          "type": ["null", "string"]
        },
        "placeOfPublication": {
          "type": ["null", "string"]
        }
      }
    },
    "themes": {
      "$ref": "refs/general.schema.json#/definitions/themes"
    },
    "spatial": {
      "$ref": "refs/general.schema.json#/definitions/Spatial"
    },
    "temporal": {
      "$ref": "refs/general.schema.json#/definitions/temporal"
    },
    "dataset": {
      "$ref": "refs/general.schema.json#/definitions/dataset"
    },
    "extraInfo": {
      "$ref": "refs/general.schema.json#/definitions/extraInfo"
    },
    "metadata": {
      "$ref": "refs/general.schema.json#/definitions/metadata"
    },
    "resource": {
      "$ref": "refs/general.schema.json#/definitions/resource"
    },
    "keywords": {
      "$ref": "refs/general.schema.json#/definitions/keywords"
    },
    "maintenanceInformation": {
      "$ref": "refs/general.schema.json#/definitions/maintenanceInformation"
    },
    "references": {
      "$ref": "refs/general.schema.json#/definitions/references"
    },
    "graphicOverviews": {
      "$ref": "refs/general.schema.json#/definitions/graphicOverviews"
    },
    "digitalTransferOptions": {
      "$ref": "refs/general.schema.json#/definitions/digitalTransferOptions"
    },
    "categoryCatalog": {
      "$ref": "refs/general.schema.json#/definitions/categoryCatalog"
    },
    "databaseContent": {
      "$ref": "refs/general.schema.json#/definitions/databaseContent"
    },
    "explanation": {
      "$ref": "refs/general.schema.json#/definitions/explanation"
    },
    "methodText": {
      "$ref": "refs/general.schema.json#/definitions/methodText"
    },
    "orderInfo": {
      "$ref": "refs/general.schema.json#/definitions/orderInfo"
    },
    "distribution": {
      "$ref": "refs/general.schema.json#/definitions/distribution"
    },
    "openDataCategories": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/KeyValue"
      }
    }
  },
  "required": [
    "_uuid",
    "_type",
    "title",
    "description",
    "pointOfContact",
    "spatial",
    "temporal",
    "metadata",
    "dataset"
  ],
  "title": "Publication"
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/publication.minimal.json
{
  "_uuid": "5aaa65dc-e811-40a1-8026-d262b3d9fcf7",
  "title": "literature_5",
  "_type": "InGridPublication",
  "dataset": { "languages": ["247"] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Heyda, Waldheim, Mittelsachsen, Sachsen, 04720, Deutschland (village)",
        "value": {
          "lat1": 51.0689498,
          "lat2": 51.1089498,
          "lon1": 13.0815141,
          "lon2": 13.1215141
        }
      }
    ],
    "spatialSystems": [{ "key": "9000003" }],
    "verticalExtent": { "unitOfMeasure": null }
  },
  "keywords": {
    "free": []
  },
  "metadata": { "language": { "key": "363" } },
  "resource": { "useConstraints": [], "accessConstraints": [] },
  "temporal": {
    "event": {
      "firstPublished": "2020-11-12T23:00:00.000Z"
    },
    "status": null
  },
  "extraInfo": { "legalBasicsDescriptions": [] },
  "references": [],
  "description": "random description",
  "publication": {},
  "pointOfContact": [
    { "ref": "83f92167-6606-4182-948c-5747ad608b80", "type": { "key": "7" } }
  ],
  "digitalTransferOptions": [],
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": { "unit": null }
  }
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/publication.maximal.json
{
  "_uuid": "22dcecc1-3eb0-4fa0-839f-14ad4393a7be",
  "title": "literatur_maximal_test",
  "_type": "InGridPublication",
  "dataset": { "languages": ["113"] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Hansa, Gremmendorf, Münster-Südost, Münster, Nordrhein-Westfalen, 48155, Deutschland (allotments)",
        "value": {
          "lat1": 51.9419043,
          "lat2": 51.9439881,
          "lon1": 7.6485776,
          "lon2": 7.652429
        }
      }
    ],
    "description": "location-information",
    "spatialSystems": [{ "key": "9000002" }],
    "verticalExtent": {
      "spatialSystem": { "key": "900005" },
      "maximumValue": 8,
      "minimumValue": 7,
      "unitOfMeasure": { "key": "4" }
    }
  },
  "keywords": {
    "free": [
      {
        "label": "optional-term"
      }
    ]
  },
  "metadata": { "language": { "key": "182" } },
  "resource": {
    "purpose": "purpose1",
    "specificUsage": "use1",
    "useLimitation": "use-constraints",
    "useConstraints": [{ "title": { "key": "2" }, "source": "source-5" }],
    "accessConstraints": [{ "key": "5" }]
  },
  "temporal": {
    "event": {
      "lastModified": "2022-09-06T22:00:00.000Z"
    },
    "status": { "key": "7" },
    "data": {
      "type": "range",
      "resourceRange": {
        "end": "2022-10-30T23:00:00.000Z",
        "start": "2022-10-04T22:00:00.000Z"
      },
      "intervalFrom": "date",
      "intervalTo": "date"
    }
  },
  "extraInfo": { "legalBasicsDescriptions": [{ "key": "39" }] },
  "orderInfo": "order location",
  "references": [
    {
      "url": "https://some-url/there",
      "referenceType": "url",
      "type": { "key": "3535" },
      "title": "keys",
      "explanation": "info remarks"
    }
  ],
  "description": "full-descr",
  "publication": {
    "isbn": "isbn",
    "pages": "pages",
    "author": "author",
    "volume": "vol",
    "location": "location",
    "publisher": "hrsg",
    "explanation": "addition-info",
    "publishedIn": "which",
    "baseDataText": "basis data",
    "doi": "10.1000/1234",
    "generalResourceType": { "key": "5" },
    "resourceType": { "key": "2" },
    "publicationDate": "year",
    "publishingHouse": "publisher",
    "bibliographicData": "bibl-info",
    "placeOfPublication": "where"
  },
  "alternateTitle": "short-descr",
  "pointOfContact": [
    { "ref": "36ec9150-2f1b-4164-8221-08f9a85fc4fb", "type": { "key": "8" } }
  ],
  "graphicOverviews": [
    {
      "fileName": {
        "uri": "https://some-link-somewhere.com",
        "value": "https://some-link-somewhere.com",
        "asLink": true
      },
      "fileDescription": "url-description"
    }
  ],
  "parentIdentifier": "ident3",
  "digitalTransferOptions": [
    {
      "name": { "key": "900005" },
      "mediumNote": "storage-location",
      "transferSize": { "value": 65, "unit": { "key": "MB" } }
    }
  ],
  "maintenanceInformation": {
    "description": "remarks",
    "maintenanceAndUpdateFrequency": { "key": "1" },
    "userDefinedMaintenanceFrequency": { "unit": { "key": "5" }, "number": 3 }
  }
}
