=== informationgrid/ingrid-editor/server/src/main/resources/ingrid/schemes/specialised-task-base.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://wemove.com/schemas/ingrid/schemes/specialisedTaskBase",
  "type": "object",
  "properties": {
    "isAdVCompatible": {
      "type": ["null", "boolean"]
    },
    "_uuid": {
      "type": "string"
    },
    "_type": {
      "const": "InGridSpecialisedTask"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "alternateTitle": {
      "type": ["null", "string"]
    },
    "parentIdentifier": {
      "type": ["null", "string"]
    },
    "pointOfContact": {
      "type": "array",
      "items": {
        "$ref": "../../general.schema.json#/definitions/PointOfContact"
      },
      "minItems": 1
    },
    "advProductGroups": {
      "$ref": "refs/general.schema.json#/definitions/advProductGroups"
    },
    "themes": {
      "$ref": "refs/general.schema.json#/definitions/themes"
    },
    "spatial": {
      "$ref": "refs/general.schema.json#/definitions/Spatial"
    },
    "temporal": {
      "$ref": "refs/general.schema.json#/definitions/temporal"
    },
    "dataset": {
      "$ref": "refs/general.schema.json#/definitions/dataset"
    },
    "extraInfo": {
      "$ref": "refs/general.schema.json#/definitions/extraInfo"
    },
    "metadata": {
      "$ref": "refs/general.schema.json#/definitions/metadata"
    },
    "resource": {
      "$ref": "refs/general.schema.json#/definitions/resource"
    },
    "keywords": {
      "$ref": "refs/general.schema.json#/definitions/keywords"
    },
    "maintenanceInformation": {
      "$ref": "refs/general.schema.json#/definitions/maintenanceInformation"
    },
    "references": {
      "$ref": "refs/general.schema.json#/definitions/references"
    },
    "graphicOverviews": {
      "$ref": "refs/general.schema.json#/definitions/graphicOverviews"
    }
  },
  "required": [
    "_uuid",
    "_type",
    "title",
    "description",
    "pointOfContact",
    "spatial",
    "temporal",
    "metadata"
  ]
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/specialized-task.minimal.json
{
  "title": "aaa",
  "_uuid": "675e1034-e766-4753-99a2-444a6412127d",
  "_type": "InGridSpecialisedTask",
  "description": "Meine Beschreibung",
  "pointOfContact": [
    {
      "type": {
        "key": "7"
      },
      "ref": "3c87c74e-ea10-41a5-bc07-93a54396470e"
    }
  ],
  "keywords": {
    "free": []
  },
  "spatial": {
    "references": [
      {
        "value": {
          "lat1": 50.0153529,
          "lon1": 8.4727605,
          "lat2": 50.2271424,
          "lon2": 8.8004049
        },
        "title": "Frankfurt am Main, Hessen, Deutschland (administrative)",
        "type": "free"
      }
    ],
    "spatialSystems": [
      {
        "key": "84"
      }
    ],
    "verticalExtent": {
      "unitOfMeasure": null
    }
  },
  "temporal": {
    "event": {
      "created": "2023-01-08T23:00:00.000Z"
    },
    "status": null
  },
  "maintenanceInformation": {
    "maintenanceAndUpdateFrequency": null,
    "userDefinedMaintenanceFrequency": {
      "unit": null
    }
  },
  "metadata": {
    "language": {
      "key": "150"
    }
  },
  "dataset": {
    "languages": []
  },
  "extraInfo": {
    "legalBasicsDescriptions": []
  },
  "resource": {},
  "references": []
}

=== informationgrid/ingrid-editor/server/src/test/resources/export/ingrid/specialized-task.maximal.json
{
  "title": "ab",
  "_uuid": "9635856b-ad0c-45c2-ae28-fbde3e56411b",
  "_type": "InGridSpecialisedTask",
  "dataset": { "languages": ["126"] },
  "spatial": {
    "references": [
      {
        "type": "free",
        "title": "Niebra, Gera, Thüringen, 07551, Deutschland (village)",
        "value": {
          "lat1": 50.8014664,
          "lat2": 50.8414664,
          "lon1": 12.0917058,
          "lon2": 12.1317058
        }
      }
    ],
    "description": "text",
    "spatialSystems": [{ "key": "9000011" }],
    "verticalExtent": {
      "Datum": { "key": "900011" },
      "maximumValue": 4,
      "minimumValue": 3,
      "unitOfMeasure": { "key": "9001" }
    }
  },
  "keywords": {
    "free": [
      {
        "label": "any keyword"
      }
    ]
  },
  "metadata": { "language": { "key": "126" } },
  "resource": { "purpose": "zweck1", "specificUsage": "nutzung1" },
  "temporal": {
    "event": {
      "lastModified": "2020-10-08T22:00:00.000Z"
    },
    "status": { "key": "6" },
    "data": {
      "type": "range",
      "resourceDate": "2020-10-11T22:00:00.000Z",
      "intervalFrom": "date",
      "intervalTo": "not-available"
    }
  },
  "extraInfo": { "legalBasicsDescriptions": [{ "key": "43" }] },
  "references": [
    {
      "url": "someUrl",
      "referenceType": "url",
      "type": { "key": "5305" },
      "title": "reference title",
      "explanation": "reference information"
    }
  ],
  "description": "full doc",
  "alternateTitle": "brief description",
  "pointOfContact": [
    { "ref": "826cd85e-9b65-43f6-b2a7-3f20b57450f4", "type": { "key": "11" } }
  ],
  "graphicOverviews": [
    {
      "fileName": {
        "uri": "https://cypress.io/something",
        "value": "https://cypress.io/something",
        "asLink": true
      },
      "fileDescription": "some url"
    }
  ],
  "parentIdentifier": "identificator",
  "maintenanceInformation": {
    "description": "info",
    "maintenanceAndUpdateFrequency": { "key": "1" },
    "userDefinedMaintenanceFrequency": { "unit": { "key": "5" }, "number": 3 }
  }
}
